/* Banca de intrebari - Profceiss Academy
   Format: { level, cat:'Electrica'|'Fotovoltaice', type, q, opts:[...], correct:index, explain, img? }
   correct = indexul raspunsului corect in lista opts (inainte de amestecare). */
const SVG_MOTOR='<svg viewBox="0 0 240 140" width="240" height="140" xmlns="http://www.w3.org/2000/svg">'+
  '<rect x="10" y="20" width="60" height="40" rx="4" fill="#dfe5ee" stroke="#5d6b82"/><text x="40" y="16" font-size="9" text-anchor="middle" fill="#34507a">ALIMENTARE</text>'+
  '<text x="22" y="74" font-size="9" fill="#e23b3b">L1</text><text x="40" y="74" font-size="9" fill="#8a5a2b">L2</text><text x="58" y="74" font-size="9" fill="#7d8794">L3</text>'+
  '<line x1="24" y1="60" x2="150" y2="60" stroke="#e23b3b" stroke-width="3"/><line x1="42" y1="60" x2="42" y2="95" stroke="#8a5a2b" stroke-width="3"/><line x1="60" y1="60" x2="60" y2="95" stroke="#7d8794" stroke-width="3"/>'+
  '<line x1="150" y1="60" x2="150" y2="95" stroke="#e23b3b" stroke-width="3"/>'+
  '<circle cx="120" cy="100" r="26" fill="#d3dbe6" stroke="#5d6b82" stroke-width="2"/><text x="120" y="104" font-size="14" text-anchor="middle" font-weight="700" fill="#34507a">M</text><text x="120" y="118" font-size="8" text-anchor="middle" fill="#5d6b82">3~</text>'+
  '<text x="92" y="96" font-size="9">U</text><text x="118" y="134" font-size="9">V</text><text x="146" y="96" font-size="9">W</text></svg>';
const SVG_BREAKER='<svg viewBox="0 0 200 140" width="200" height="140" xmlns="http://www.w3.org/2000/svg">'+
  '<rect x="70" y="20" width="40" height="80" rx="4" fill="#f4f6f8" stroke="#9aa7bb" stroke-width="1.6"/>'+
  '<rect x="78" y="34" width="24" height="14" rx="2.5" fill="#1f9d57"/><text x="90" y="45" font-size="9" text-anchor="middle" fill="#fff" font-weight="700">I</text>'+
  '<text x="90" y="92" font-size="9" text-anchor="middle" fill="#34507a" font-weight="700">C16</text>'+
  '<line x1="90" y1="20" x2="90" y2="6" stroke="#e23b3b" stroke-width="3"/><text x="96" y="14" font-size="9" fill="#e23b3b">L</text>'+
  '<line x1="90" y1="100" x2="90" y2="120" stroke="#e23b3b" stroke-width="3"/><line x1="40" y1="120" x2="160" y2="120" stroke="#2f6fd0" stroke-width="3"/><text x="150" y="116" font-size="9" fill="#2f6fd0">N</text>'+
  '<line x1="90" y1="120" x2="90" y2="120" stroke="#2f6fd0"/><path d="M120 100 l-6 12 l5 0 l-4 10 l11 -14 l-5 0 l4 -8 z" fill="#ffd23d" stroke="#c0392b" stroke-width="1"/></svg>';

const QUESTIONS=[
  // ====================== BEGINNER - ELECTRICA ======================
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce culoare are conductorul de protectie (impamantare, PE)?',
    opts:['Galben-verde','Albastru','Rosu','Negru'], correct:0,
    explain:'PE este intotdeauna galben-verde.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce culoare are conductorul de nul (neutru, N)?',
    opts:['Rosu','Maro','Albastru','Galben-verde'], correct:2,
    explain:'Nulul de lucru este albastru.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce culoare poate avea conductorul de faza?',
    opts:['Albastru','Galben-verde','Verde','Maro sau negru'], correct:3,
    explain:'Faza este uzual maro, negru sau gri.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Care este tensiunea intre faza si nul intr-o locuinta din Romania?',
    opts:['24 V','230 V','400 V','110 V'], correct:1,
    explain:'Monofazat: 230 V intre faza si nul.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Care este tensiunea intre doua faze intr-un sistem trifazat?',
    opts:['230 V','120 V','400 V','690 V'], correct:2,
    explain:'Intre doua faze sunt aproximativ 400 V.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce reprezinta faza intr-o instalatie electrica?',
    opts:['Conductorul aflat sub tensiune','Conductorul legat la pamant','Carcasa metalica','Bara de nul'], correct:0,
    explain:'Faza este conductorul sub tensiune care alimenteaza consumatorul.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce rol are conductorul de nul (N)?',
    opts:['Mareste tensiunea','Inchide circuitul, asigura calea de retur a curentului','Protejeaza la fulgere','Stocheaza energie'], correct:1,
    explain:'Nulul inchide circuitul, fiind calea de intoarcere a curentului.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce rol are impamantarea (PE)?',
    opts:['Alimenteaza becul','Reduce factura','Pune carcasele metalice la pamant pentru siguranta','Mareste curentul'], correct:2,
    explain:'PE leaga partile metalice la pamant pentru protectia persoanelor.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce sectiune de cablu se foloseste uzual pentru un circuit de prize?',
    opts:['0,75 mmp','2,5 mmp','1,5 mmp','10 mmp'], correct:1,
    explain:'Prizele se executa uzual cu 2,5 mmp, protejate la 16 A.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce sectiune de cablu se foloseste uzual pentru un circuit de iluminat?',
    opts:['1,5 mmp','2,5 mmp','4 mmp','6 mmp'], correct:0,
    explain:'Iluminatul se executa uzual cu 1,5 mmp, protejat la 10 A.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Care dintre acestea este o sectiune uzuala de conductor?',
    opts:['3,7 mmp','2,5 mmp','5,1 mmp','8 mmp'], correct:1,
    explain:'Sectiunile uzuale sunt 1,5 / 2,5 / 4 / 6 mmp.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce siguranta automata se potriveste cu un cablu de 2,5 mmp pentru prize?',
    opts:['63 A','40 A','16 A','6 A'], correct:2,
    explain:'2,5 mmp suporta uzual maxim 16-20 A; tipic se pune 16 A.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce siguranta automata se foloseste uzual pe un circuit de iluminat (1,5 mmp)?',
    opts:['10 A','32 A','25 A','40 A'], correct:0,
    explain:'Pentru 1,5 mmp la iluminat se pune uzual 10 A.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Care dintre acestea NU este un calibru uzual de siguranta automata?',
    opts:['16 A','20 A','25 A','17 A'], correct:3,
    explain:'Calibrele uzuale sunt 10/16/20/25/32 A; 17 A nu exista standard.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Care este rolul principal al diferentialului (RCD de 30 mA)?',
    opts:['Mareste tensiunea','Reduce consumul','Protejeaza persoanele la electrocutare','Stocheaza energie'], correct:2,
    explain:'RCD-ul de 30 mA detecteaza curentul de fuga si protejeaza omul.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce protejeaza o siguranta automata (MCB)?',
    opts:['Circuitul la suprasarcina si scurtcircuit','Doar la fulgere','Persoanele la electrocutare','Bateria'], correct:0,
    explain:'MCB-ul protejeaza cablul/circuitul; persoanele le protejeaza RCD-ul.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Care este diferenta principala intre o siguranta automata si un diferential?',
    opts:['Sunt acelasi lucru','Siguranta protejeaza cablul, diferentialul protejeaza omul','Diferentialul mareste curentul','Siguranta stocheaza energie'], correct:1,
    explain:'MCB protejeaza circuitul la supracurent, RCD protejeaza omul la curent de fuga.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Daca legi faza direct la nul, fara niciun consumator, ce se intampla?', img:SVG_BREAKER,
    opts:['Nu se intampla nimic','Becul se aprinde slab','Scurtcircuit: curent foarte mare, siguranta declanseaza','Creste tensiunea'], correct:2,
    explain:'Faza legata direct la nul = scurtcircuit; siguranta sare ca sa protejeze.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Intr-un circuit de iluminat cu intrerupator, ce conductor se intrerupe?',
    opts:['Nulul','Impamantarea','Toate trei','Faza (prin intrerupator)'], correct:3,
    explain:'Intrerupatorul taie faza; nulul si PE merg direct la corpul de iluminat.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'O priza cu impamantare (tip schuko) are in plus fata de una simpla:',
    opts:['Contact de protectie (PE)','Un al treilea pol de faza','Un fuzibil','Un contor'], correct:0,
    explain:'Priza schuko are contactul de impamantare pentru siguranta.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'In tablou, unde se leaga nulul de lucru al circuitelor?',
    opts:['La faza','La carcasa','La bara de nul (N)','La bara de PE'], correct:2,
    explain:'Nulurile circuitelor se aduna pe bara de nul.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Cum se calculeaza puterea electrica intr-un circuit simplu?',
    opts:['P = U / I','P = U x I (tensiune x curent)','P = I / U','P = U + I'], correct:1,
    explain:'Puterea = tensiune inmultita cu curent.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Un consumator de 230 V trage 10 A. Ce putere are aproximativ?',
    opts:['23 W','2300 W','230 W','100 W'], correct:1,
    explain:'P = U x I = 230 x 10 = 2300 W.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce este curentul alternativ (AC)?',
    opts:['Curent care isi schimba periodic sensul','Curent care curge intr-un singur sens','Curent fara tensiune','Curent doar din baterie'], correct:0,
    explain:'AC isi schimba sensul periodic (50 Hz in retea).' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce este curentul continuu (DC)?',
    opts:['Curent care isi schimba sensul','Curent care curge intr-un singur sens','Curent de inalta frecventa','Tensiune zero'], correct:1,
    explain:'DC curge intr-un singur sens, ca la baterie sau panou PV.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Care este frecventa retelei electrice in Romania?',
    opts:['60 Hz','100 Hz','50 Hz','25 Hz'], correct:2,
    explain:'Reteaua din Romania functioneaza la 50 Hz.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Unde se monteaza intrerupatorul fata de bec?',
    opts:['Pe nul','Pe faza, inaintea becului','Pe PE','Dupa bec, pe nul'], correct:1,
    explain:'Intrerupatorul se monteaza pe faza pentru ca becul sa ramana fara tensiune cand e stins.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce inseamna 16 A scris pe o siguranta automata?',
    opts:['Tensiunea','Curentul nominal pe care il suporta','Puterea in W','Numarul de circuite'], correct:1,
    explain:'16 A este curentul nominal al sigurantei.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Daca un circuit de 16 A trage 20 A timp indelungat, siguranta automata:',
    opts:['Declanseaza (protejeaza cablul de supraincalzire)','Lasa sa treaca','Creste tensiunea','Se transforma in RCD'], correct:0,
    explain:'La suprasarcina, MCB-ul declanseaza ca sa nu se incalzeasca cablul.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Cablul CYY-F 3x2,5 contine:',
    opts:['Un singur conductor','5 conductoare','2 conductoare','3 conductoare de 2,5 mmp (faza, nul, PE)'], correct:3,
    explain:'3x2,5 = trei conductoare de 2,5 mmp.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce instrument masoara tensiunea?',
    opts:['Voltmetrul','Ampermetrul','Wattmetrul','Cronometrul'], correct:0,
    explain:'Tensiunea se masoara cu voltmetrul, in volti.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'In ce unitate se masoara curentul electric?',
    opts:['Volt','Watt','Amper','Ohm'], correct:2,
    explain:'Curentul se masoara in amperi (A).' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ridici siguranta principala si ea sare imediat la loc (declanseaza). Ce inseamna?', img:SVG_BREAKER,
    opts:['Totul e in regula','Tensiunea e prea mica','Exista un scurtcircuit pe instalatie','Lipseste nulul'], correct:2,
    explain:'Declansarea imediata indica un scurtcircuit sau o suprasarcina mare.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce inseamna ca un consumator are 2000 W?',
    opts:['Consuma 2000 wati de putere','Are 2000 V tensiune','Are 2000 A curent','Costa 2000 lei'], correct:0,
    explain:'2000 W este puterea consumatorului.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'La un tablou monofazat, cati conductori intra de la retea?',
    opts:['Un conductor','Faza, nul si PE (3 conductoare)','Doar faza','Cinci conductoare'], correct:1,
    explain:'Monofazat: faza, nul si PE.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Cati conductori de faza are alimentarea trifazata?',
    opts:['1','2','3','4'], correct:2,
    explain:'Trifazat: 3 faze (L1, L2, L3), plus nul si PE.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce se intampla daca atingi un conductor de faza neizolat?',
    opts:['Nimic','Risc de electrocutare','Se incarca bateria','Scade tensiunea'], correct:1,
    explain:'Atingerea fazei sub tensiune prezinta risc de electrocutare.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Inainte de a lucra la o instalatie, ce faci mai intai?',
    opts:['Maresti siguranta','Scoti tensiunea si verifici lipsa ei','Pui mai multe prize','Cresti sectiunea'], correct:1,
    explain:'Se deconecteaza tensiunea si se verifica lipsa ei cu un tester.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Cu ce verifici rapid daca un conductor are tensiune?',
    opts:['Cu surubelnita de test / creion de tensiune','Cu ruleta','Cu ciocanul','Cu mana'], correct:0,
    explain:'Se foloseste un creion de tensiune sau tester, niciodata mana.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ca sa poti pune o siguranta mai mare de 16 A, trebuie sa:',
    opts:['Maresti sectiunea cablului','Micsorezi cablul','Scoti nulul','Pui doua faze'], correct:0,
    explain:'Siguranta nu poate depasi capacitatea cablului; intai maresti sectiunea.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce sectiune se foloseste uzual pentru un circuit de aragaz electric / cuptor?',
    opts:['1,5 mmp','0,75 mmp','4 mmp sau 6 mmp','0,5 mmp'], correct:2,
    explain:'Consumatorii mari (cuptor, plita) cer 4 sau 6 mmp.' },
  { level:'beginner', cat:'Electrica', type:'single', q:'Ce este rezistenta electrica?',
    opts:['Opozitia la trecerea curentului, in ohmi','Cantitatea de energie','Viteza curentului','Numarul de prize'], correct:0,
    explain:'Rezistenta este opozitia la curent, masurata in ohmi.' },

  // ====================== BEGINNER - FOTOVOLTAICE ======================
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Un panou fotovoltaic produce curent:',
    opts:['Alternativ (AC)','Continuu (DC)','Trifazat direct','De inalta frecventa'], correct:1,
    explain:'Panourile produc curent continuu (DC).' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Ce face invertorul intr-un sistem fotovoltaic?',
    opts:['Transforma AC in DC','Stocheaza energie','Transforma curentul continuu (DC) in alternativ (AC)','Mareste tensiunea retelei'], correct:2,
    explain:'Invertorul converteste DC de la panouri in AC pentru casa/retea.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Conectarea panourilor in SERIE (string) creste:',
    opts:['Tensiunea (V)','Curentul (A)','Numarul de invertoare','Greutatea pe acoperis'], correct:0,
    explain:'In serie se aduna tensiunile; curentul ramane acelasi.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Conectarea panourilor in PARALEL creste:',
    opts:['Tensiunea (V)','Frecventa','Curentul (A)','Rezistenta'], correct:2,
    explain:'In paralel se aduna curentii; tensiunea ramane aceeasi.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Cine este un prosumator?',
    opts:['Doar cel care consuma','Furnizorul de energie','Operatorul de distributie','Cel care produce si consuma energie, injectand surplusul in retea'], correct:3,
    explain:'Prosumatorul produce energie (PV) si o consuma, livrand surplusul in retea.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Care este orientarea optima a panourilor in Romania (emisfera nordica)?',
    opts:['Spre sud','Spre nord','Spre vest obligatoriu','Spre pamant'], correct:0,
    explain:'In emisfera nordica, orientarea spre sud da productia maxima.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Un "string" fotovoltaic inseamna:',
    opts:['Un singur panou','Un grup de panouri legate in serie','Bateria sistemului','Cablul de retea'], correct:1,
    explain:'String = sir de panouri conectate in serie.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Capacitatea unei baterii de stocare se masoara in:',
    opts:['Litri','Amperi pe metru','kWh (kilowati-ora)','Ohmi'], correct:2,
    explain:'Bateria se dimensioneaza in kWh (energie stocata).' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Ce permite un sistem fotovoltaic HIBRID fata de unul on-grid simplu?',
    opts:['Stocarea energiei in baterie','Sa produca mai multa tensiune','Sa nu mai aiba nevoie de invertor','Sa functioneze fara panouri'], correct:0,
    explain:'Sistemul hibrid poate incarca o baterie pentru consum ulterior.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Cand produce un panou fotovoltaic cea mai multa energie?',
    opts:['Noaptea','Pe ceata densa','Ziua, cu soare puternic','Cand ploua'], correct:2,
    explain:'Productia maxima e ziua, sub radiatie solara puternica.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Din ce material sunt facute majoritatea panourilor fotovoltaice?',
    opts:['Aluminiu','Siliciu','Cupru','Sticla simpla'], correct:1,
    explain:'Celulele fotovoltaice sunt facute uzual din siliciu.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'In ce unitate se exprima puterea unui panou fotovoltaic?',
    opts:['kWh','Wp (wati-peak)','Amperi-ora','Litri'], correct:1,
    explain:'Puterea de varf a unui panou se da in Wp.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Un sistem ON-GRID (la retea) fara baterie, ce face cu surplusul de energie?',
    opts:['Il pierde complet','Il injecteaza in reteaua publica','Il transforma in caldura','Il stocheaza intern'], correct:1,
    explain:'Sistemul on-grid livreaza surplusul in retea.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Ce este un sistem OFF-GRID?',
    opts:['Conectat permanent la retea','Independent de retea, cu baterii','Doar pentru fabrici','Fara panouri'], correct:1,
    explain:'Off-grid functioneaza izolat, bazat pe baterii.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Ce se intampla cu productia daca un panou e umbrit partial?',
    opts:['Creste productia','Scade productia stringului','Nu conteaza deloc','Creste tensiunea'], correct:1,
    explain:'Umbrirea reduce productia, mai ales pe un string in serie.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'La ce serveste structura de montaj a panourilor?',
    opts:['Sa fixeze panourile la unghiul corect pe acoperis','Sa produca curent','Sa stocheze energie','Sa transforme DC in AC'], correct:0,
    explain:'Structura fixeaza si orienteaza panourile.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Un invertor on-grid de 5 kW alimenteaza:',
    opts:['Doar bateria','Consumul casei si trimite surplusul in retea','Doar reteaua','Nimic'], correct:1,
    explain:'Invertorul on-grid alimenteaza casa si injecteaza surplusul.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Ce inseamna kWp pentru un sistem fotovoltaic?',
    opts:['Energia anuala','Puterea instalata de varf a panourilor','Capacitatea bateriei','Curentul maxim'], correct:1,
    explain:'kWp este puterea de varf instalata in panouri.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Iarna, cu zile scurte, productia fotovoltaica este:',
    opts:['Mai mare ca vara','Mai mica decat vara','La fel ca vara','Zero mereu'], correct:1,
    explain:'Iarna soarele e mai slab si zilele scurte, deci productia scade.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'De ce se curata panourile fotovoltaice de praf si frunze?',
    opts:['Ca sa fie frumoase','Ca sa nu scada productia','Ca sa creasca tensiunea','Nu e nevoie niciodata'], correct:1,
    explain:'Murdaria reduce lumina ajunsa la celule si scade productia.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Curentul produs de un panou ajunge la casa prin:',
    opts:['Direct, fara nimic','Invertor, care il transforma in AC','Doar prin baterie','Prin contorul de apa'], correct:1,
    explain:'DC-ul de la panou trece prin invertor si devine AC utilizabil.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Pe partea de curent continuu (DC) a stringurilor se monteaza pentru protectie:',
    opts:['Doar un intrerupator de lumina','Nimic, nu e nevoie','Sectionare/sigurante DC si descarcatoare (SPD)','Un contor de apa'], correct:2,
    explain:'Partea DC are nevoie de sectionare, sigurante DC si protectie la supratensiune (SPD).' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Ce face un controler de incarcare intr-un sistem off-grid?',
    opts:['Gestioneaza incarcarea bateriei de la panouri','Mareste numarul de panouri','Schimba culoarea cablurilor','Produce caldura'], correct:0,
    explain:'Controlerul de incarcare regleaza curentul spre baterie.' },
  { level:'beginner', cat:'Fotovoltaice', type:'single', q:'Ce inseamna autoconsum la un prosumator?',
    opts:['Energia vanduta integral','Energia produsa si folosita direct in casa','Energia pierduta','Energia din baterie noaptea doar'], correct:1,
    explain:'Autoconsumul e energia PV folosita direct in casa.' },

  // ====================== PRO - ELECTRICA ======================
  { level:'pro', cat:'Electrica', type:'single', q:'Pentru un cablu de 1,5 mmp, ce siguranta automata maxima se recomanda?',
    opts:['25 A','16 A','10 A','32 A'], correct:2,
    explain:'1,5 mmp se protejeaza uzual la 10 A (max 16 A in conditii bune).' },
  { level:'pro', cat:'Electrica', type:'single', q:'Pentru un cablu de 4 mmp, ce siguranta automata se potriveste uzual?',
    opts:['10 A','16 A','25 A','63 A'], correct:2,
    explain:'4 mmp suporta uzual pana la 25-32 A; tipic 25 A.' },
  { level:'pro', cat:'Electrica', type:'single', q:'De ce nu se pune o siguranta de 32 A pe un cablu de 1,5 mmp?',
    opts:['Cablul se poate supraincalzi si aprinde inainte sa declanseze','Nu intra in tablou','Costa prea mult','Schimba culoarea fazei'], correct:0,
    explain:'Siguranta trebuie sa protejeze cablul; 32 A pe 1,5 mmp duce la supraincalzire.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Ce se intampla daca inversezi doua faze la un motor trifazat?', img:SVG_MOTOR,
    opts:['Motorul se invarte in sens invers','Motorul se arde','Motorul merge mai repede','Nu porneste deloc'], correct:0,
    explain:'Inversarea a doua faze schimba sensul de rotatie.' },
  { level:'pro', cat:'Electrica', type:'single', q:'De cate faze are nevoie un motor trifazat ca sa porneasca normal?',
    opts:['O singura faza','Doar nul si PE','3 faze diferite (L1, L2, L3)','Doua faze'], correct:2,
    explain:'Motorul trifazat are nevoie de cele 3 faze pe bornele U, V, W.' },
  { level:'pro', cat:'Electrica', type:'single', q:'La un bec comandat cu intrerupator, prin intrerupator trebuie sa treaca:',
    opts:['Nulul','Faza','PE-ul','Ambele faze'], correct:1,
    explain:'Faza trece prin intrerupator, ca becul sa fie fara tensiune cand e stins.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Ce tip de RCD se foloseste cand exista consumatori electronici (invertoare, masini de spalat moderne)?',
    opts:['Tip AC','Tip A','Tip simplu fara clasa','Niciun tip'], correct:1,
    explain:'RCD tip A detecteaza si componenta continua pulsatorie, necesara la electronice.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Ce detecteaza un RCD de tip AC?',
    opts:['Doar curenti de fuga alternativi sinusoidali','Curenti continui puri','Supratensiuni','Frecventa'], correct:0,
    explain:'Tip AC reactioneaza doar la curenti de fuga alternativi.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Cablul CYABY este un cablu:',
    opts:['Pentru lipit electronice','Armat, pentru pozare ingropata in pamant','De telefonie','Doar pentru iluminat interior'], correct:1,
    explain:'CYABY este armat, potrivit pentru pozare ingropata.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Caderea de tensiune pe un cablu creste atunci cand:',
    opts:['Scade lungimea','Creste sectiunea','Creste lungimea si curentul','Scade curentul'], correct:2,
    explain:'Caderea de tensiune creste cu lungimea si curentul, scade cu sectiunea.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Cum reduci caderea de tensiune pe o linie lunga?',
    opts:['Maresti sectiunea conductorului','Micsorezi sectiunea','Scoti nulul','Reduci tensiunea'], correct:0,
    explain:'O sectiune mai mare reduce rezistenta si caderea de tensiune.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Intr-o comanda de motor cu contactor, butonul de START este uzual:',
    opts:['Contact normal inchis (NC)','Contact normal deschis (NO)','Un releu termic','O siguranta'], correct:1,
    explain:'Butonul START este NO: la apasare inchide circuitul.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Intr-o comanda de motor cu contactor, butonul de STOP este uzual:',
    opts:['Contact normal deschis (NO)','Contact normal inchis (NC)','Un descarcator','Un MPPT'], correct:1,
    explain:'Butonul STOP este NC: la apasare intrerupe circuitul.' },
  { level:'pro', cat:'Electrica', type:'single', q:'La ce serveste contactul de auto-mentinere intr-o schema cu contactor?',
    opts:['Mentine contactorul actionat dupa eliberarea butonului START','Opreste motorul','Schimba sensul','Reduce tensiunea'], correct:0,
    explain:'Auto-mentinerea pastreaza bobina alimentata dupa ce s-a eliberat START.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Ce rol are releul termic intr-un circuit de motor?',
    opts:['Mareste turatia','Protejeaza motorul la suprasarcina (supracurent prelungit)','Transforma DC in AC','Stocheaza energie'], correct:1,
    explain:'Releul termic deconecteaza motorul la suprasarcina prelungita.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Ce comanda un contactor?',
    opts:['Inchiderea/deschiderea unui circuit de putere prin bobina de comanda','Doar iluminatul de avarie','Tensiunea retelei','Capacitatea bateriei'], correct:0,
    explain:'Contactorul comuta circuite de putere cu ajutorul bobinei.' },
  { level:'pro', cat:'Electrica', type:'single', q:'O schema monofilara reprezinta:',
    opts:['Instalatia simplificat, cu o singura linie pentru un circuit','Toti conductorii desenati separat','Doar bateria','Doar invertorul'], correct:0,
    explain:'Schema monofilara arata circuitele cu o singura linie, simplificat.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Ordinea corecta a aparatelor in tablou, de la retea spre circuite, este:',
    opts:['Sigurante -> diferential -> general','General -> diferential -> sigurante de circuit','Diferential -> general -> sigurante','Random'], correct:1,
    explain:'Intai siguranta generala, apoi diferentialul, apoi sigurantele pe circuite.' },
  { level:'pro', cat:'Electrica', type:'single', q:'De ce se grupeaza circuitele sub mai multe diferentiale in tablou?',
    opts:['Ca un defect pe un circuit sa nu opreasca toata casa','Ca sa coste mai mult','Ca sa creasca tensiunea','Fara motiv'], correct:0,
    explain:'Gruparea limiteaza zona afectata la declansarea unui RCD.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Pentru un consumator trifazat, ce siguranta se foloseste?',
    opts:['Una monopolara','O siguranta tripolara (3 poli)','Doar diferential','O priza schuko'], correct:1,
    explain:'Consumatorul trifazat se protejeaza cu siguranta tripolara.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Ce semnifica curba C la o siguranta automata (ex. C16)?',
    opts:['Declanseaza magnetic la 5-10 x curentul nominal','Este pentru curent continuu','Are 16 poli','Indica tensiunea'], correct:0,
    explain:'Curba C declanseaza magnetic intre 5 si 10 ori In, potrivita uzual casnic.' },
  { level:'pro', cat:'Electrica', type:'single', q:'La inversarea sensului unui motor trifazat se intervine asupra:',
    opts:['Nulului','A doua dintre cele trei faze','Conductorului PE','Tensiunii de comanda'], correct:1,
    explain:'Se inverseaza doua faze pentru a schimba sensul de rotatie.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Sectiunea cablului de alimentare trebuie aleasa in functie de:',
    opts:['Curentul consumatorului, lungime si modul de pozare','Culoarea peretelui','Numarul de prize din casa','Marca tabloului'], correct:0,
    explain:'Sectiunea se alege dupa curent, lungime, cadere de tensiune si pozare.' },
  { level:'pro', cat:'Electrica', type:'single', q:'De ce nu se leaga nulul de lucru (N) la bara de PE intr-un sistem TT?',
    opts:['Ca sa nu apara tensiune periculoasa pe carcase la curent de retur','Ca sa creasca puterea','Nu conteaza','Ca sa scada factura'], correct:0,
    explain:'Amestecarea N cu PE poate aduce tensiune pe carcase si dezechilibra protectiile.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Un consumator de 3,5 kW pe 230 V trage aproximativ:',
    opts:['1,5 A','15 A','150 A','0,5 A'], correct:1,
    explain:'I = P/U = 3500/230 = aproximativ 15 A.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Ce protejeaza in plus un disjunctor diferential (RCBO)?',
    opts:['Doar la scurtcircuit','Si la supracurent, si la curent de fuga','Doar la fulgere','Nimic special'], correct:1,
    explain:'RCBO combina protectia la supracurent (MCB) cu cea diferentiala (RCD).' },

  // ====================== PRO - FOTOVOLTAICE ======================
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Cum se dimensioneaza uzual invertorul fata de puterea panourilor?',
    opts:['Invertorul mult mai mare ca panourile','Apropiat de puterea panourilor (raport DC/AC tipic 1,0-1,3)','De 5 ori mai mic','Nu conteaza raportul'], correct:1,
    explain:'Se urmareste un raport DC/AC tipic intre 1,0 si 1,3.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Ce este MPPT-ul unui invertor?',
    opts:['Un tip de baterie','Urmarirea punctului de putere maxima a panourilor','Un descarcator','Un contor'], correct:1,
    explain:'MPPT (Maximum Power Point Tracking) extrage puterea maxima din panouri.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'De ce are un invertor mai multe intrari MPPT?',
    opts:['Ca sa optimizeze separat stringuri cu orientari/umbriri diferite','Ca sa fie mai greu','Pentru baterie obligatoriu','Ca sa scada tensiunea'], correct:0,
    explain:'Mai multe MPPT permit optimizarea stringurilor cu conditii diferite.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Care este unghiul de inclinare uzual recomandat pentru panouri in Romania?',
    opts:['Aproape 0 grade (orizontal)','Aproximativ 30-35 grade','90 grade (vertical)','Nu conteaza'], correct:1,
    explain:'Un unghi de aproximativ 30-35 grade da o productie anuala buna in Romania.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Cate panouri pot intra pe un string depinde in principal de:',
    opts:['Culoarea panoului','Tensiunea maxima admisa la intrarea invertorului','Greutatea structurii','Marca cablului'], correct:1,
    explain:'Numarul de panouri in serie e limitat de tensiunea max a invertorului.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Pe partea DC, sigurantele fuzibile (string) au rolul de a:',
    opts:['Mari curentul','Proteja la supracurent in caz de defect intre stringuri','Transforma DC in AC','Stoca energie'], correct:1,
    explain:'Sigurantele DC protejeaza stringurile la supracurent de retur.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Ce rol are sectionatorul DC (intrerupatorul DC)?',
    opts:['Permite separarea panourilor de invertor in siguranta','Produce energie','Mareste tensiunea','Inlocuieste bateria'], correct:0,
    explain:'Sectionatorul DC izoleaza panourile de invertor pentru interventii sigure.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Ce este un SPD (descarcator) montat pe partea DC?',
    opts:['Un contor','Protectie la supratensiuni (ex. trasnet indirect)','Un invertor mic','O baterie'], correct:1,
    explain:'SPD protejeaza echipamentele la supratensiuni atmosferice/de comutatie.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Intr-un sistem hibrid, bateria se conecteaza uzual la:',
    opts:['Direct in priza casei','Invertorul hibrid (cu port de baterie)','Contorul de apa','Reteaua de gaz'], correct:1,
    explain:'Bateria se leaga la invertorul hibrid prevazut cu port de stocare.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Ce cablu se foloseste uzual pe partea DC a panourilor?',
    opts:['Cablu solar special (rezistent UV, dublu izolat)','Cablu de telefon','Cablu de difuzor','Orice cablu de iluminat'], correct:0,
    explain:'Se foloseste cablu solar dedicat, rezistent la UV si temperatura.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Ce conectori se folosesc uzual intre panourile fotovoltaice?',
    opts:['Conectori MC4','Mufe schuko','Cleme de telefon','Papuci de cupru simpli'], correct:0,
    explain:'Conectorii MC4 sunt standardul pentru legaturi DC intre panouri.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Daca legi un string cu tensiune prea mare pentru invertor, riscul este:',
    opts:['Productie mai mare','Deteriorarea invertorului la depasirea tensiunii maxime','Nimic','Scade curentul util'], correct:1,
    explain:'Depasirea tensiunii maxime DC poate distruge invertorul.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Un sistem hibrid trece pe baterie cand:',
    opts:['Soarele e foarte puternic','Productia PV nu acopera consumul sau e noapte','Tensiunea retelei creste','Niciodata'], correct:1,
    explain:'Bateria acopera consumul cand PV nu ajunge (sau noaptea).' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Ce inseamna functia backup / EPS a unui invertor hibrid?',
    opts:['Mareste productia vara','Alimenteaza consumatori critici la caderea retelei','Curata panourile','Schimba unghiul panourilor'], correct:1,
    explain:'Backup/EPS asigura energie la consumatori critici cand cade reteaua.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'De ce se evita stringuri cu panouri de orientari diferite pe acelasi MPPT?',
    opts:['Productia stringului scade la nivelul celui mai slab panou','Creste tensiunea periculos','Se aprind panourile','Nu e nicio problema'], correct:0,
    explain:'Pe acelasi MPPT, panoul cel mai slab limiteaza intregul string.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Un optimizor de putere montat pe panou ajuta la:',
    opts:['Reducerea pierderilor cauzate de umbrire partiala','Stocarea energiei','Marirea tensiunii retelei','Racirea casei'], correct:0,
    explain:'Optimizoarele reduc impactul umbririi, optimizand fiecare panou.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Pentru un consum casnic mediu, un sistem rezidential tipic are puterea de:',
    opts:['0,2 kWp','3-6 kWp','200 kWp','1000 kWp'], correct:1,
    explain:'Rezidential tipic: 3-6 kWp, in functie de consum si acoperis.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Ce rol are contorul bidirectional la un prosumator?',
    opts:['Masoara doar consumul','Masoara separat energia consumata si cea injectata in retea','Produce energie','Stocheaza energie'], correct:1,
    explain:'Contorul bidirectional inregistreaza atat consumul cat si injectia.' },

  // ====================== EXPERT - ELECTRICA ======================
  { level:'expert', cat:'Electrica', type:'single', q:'In schema TN-S, conductorul de nul (N) si cel de protectie (PE):',
    opts:['Sunt acelasi conductor','Sunt separate pe tot traseul','Lipsesc ambele','Sunt legate la faza'], correct:1,
    explain:'In TN-S, N si PE sunt separate pe intregul traseu.' },
  { level:'expert', cat:'Electrica', type:'single', q:'In schema TN-C-S, conductorul PEN (N+PE combinat):',
    opts:['Ramane combinat pana la consumator','Se separa in N si PE intr-un punct, apoi raman separate','Nu exista','Este faza'], correct:1,
    explain:'In TN-C-S, PEN se separa la un punct in N si PE distincte.' },
  { level:'expert', cat:'Electrica', type:'single', q:'In schema TT, masele consumatorului sunt legate la:',
    opts:['Nulul retelei','O priza de pamant proprie, locala','Faza','Bara invertorului'], correct:1,
    explain:'In TT, instalatia are propria priza de pamant, independenta de cea a retelei.' },
  { level:'expert', cat:'Electrica', type:'single', q:'In sistemul TT, protectia la atingere indirecta se asigura uzual prin:',
    opts:['Numai siguranta automata','Diferential (RCD)','Doar legare la nul','Niciun dispozitiv'], correct:1,
    explain:'In TT, impedanta buclei e mare, deci RCD-ul e esential pentru protectie.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Selectivitatea sigurantelor inseamna:',
    opts:['Toate sigurantele sar deodata','Declanseaza doar protectia cea mai apropiata de defect','Nu declanseaza niciuna','Cresterea tensiunii'], correct:1,
    explain:'Selectivitatea asigura declansarea doar a protectiei imediat amonte de defect.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Pentru selectivitate intre o siguranta generala si una de circuit, generala trebuie sa fie:',
    opts:['Mai mica decat cea de circuit','De acelasi calibru','Mai mare si/sau temporizata fata de cea de circuit','Fara legatura'], correct:2,
    explain:'Generala trebuie sa aiba calibru mai mare si eventual temporizare pentru selectivitate.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Impedanta buclei de defect determina:',
    opts:['Curentul de scurtcircuit la un defect, deci timpul de declansare','Culoarea fazei','Capacitatea bateriei','Frecventa retelei'], correct:0,
    explain:'O bucla cu impedanta mica da curent mare de defect si declansare rapida.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Ce cadere de tensiune maxima se admite uzual pe circuitele de iluminat?',
    opts:['10%','3%','5%','20%'], correct:1,
    explain:'La iluminat se urmareste tipic sub 3% cadere de tensiune.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Ce cadere de tensiune maxima se admite uzual pe circuitele de forta?',
    opts:['1%','5%','15%','25%'], correct:1,
    explain:'La circuitele de forta se admite tipic pana la 5%.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Pornirea stea-triunghi a unui motor are scopul de a:',
    opts:['Mari curentul de pornire','Reduce curentul de pornire fata de pornirea directa','Inversa sensul','Opri motorul'], correct:1,
    explain:'Pornirea stea-triunghi reduce curentul de pornire, deci socul pe retea.' },
  { level:'expert', cat:'Electrica', type:'single', q:'In pornirea stea-triunghi, motorul porneste in conexiunea:',
    opts:['Triunghi, apoi trece in stea','Stea, apoi trece in triunghi','Doar in stea permanent','Doar in triunghi permanent'], correct:1,
    explain:'Porneste in stea (curent redus) si comuta in triunghi pentru regim normal.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Factorul de putere (cos fi) scazut intr-o instalatie inductiva inseamna:',
    opts:['Putere reactiva mare, curent mai mare pentru aceeasi putere activa','Eficienta perfecta','Tensiune zero','Lipsa consumului'], correct:0,
    explain:'Un cos fi mic implica putere reactiva mare si curenti mariti.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Compensarea factorului de putere la sarcini inductive se face uzual cu:',
    opts:['Bobine suplimentare','Baterii de condensatoare','Rezistente','Mai multe faze'], correct:1,
    explain:'Condensatoarele compenseaza puterea reactiva inductiva si cresc cos fi.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Curentul de scurtcircuit prezumat (Icc) intr-un punct depinde de:',
    opts:['Culoarea cablurilor','Impedanta sursei si a traseului pana in acel punct','Numarul de prize','Marca tabloului'], correct:1,
    explain:'Icc depinde de impedanta totala de la sursa pana la punctul de defect.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Capacitatea de rupere a unui disjunctor (Icn) trebuie sa fie:',
    opts:['Mai mica decat Icc din punctul de montaj','Cel putin egala cu curentul de scurtcircuit prezumat in acel punct','Egala cu tensiunea','Fara importanta'], correct:1,
    explain:'Disjunctorul trebuie sa poata intrerupe curentul de scurtcircuit din acel punct.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Conform practicii, sectiunea conductorului PE fata de faza, pentru faza de 16 mmp, este uzual:',
    opts:['Egala cu faza (16 mmp)','Jumatate (dar minim valoarea ceruta)','De doua ori faza','Doar 1,5 mmp mereu'], correct:0,
    explain:'Pentru faze pana la 16 mmp, PE se ia egal cu sectiunea fazei.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Pentru o faza de 35 mmp, sectiunea minima a PE este uzual:',
    opts:['35 mmp','1,5 mmp','Jumatate, adica 16 mmp','70 mmp'], correct:2,
    explain:'Peste 16 mmp, PE poate fi jumatate din sectiunea fazei (aici 16 mmp).' },
  { level:'expert', cat:'Electrica', type:'single', q:'Normativul I7 reglementeaza in principal:',
    opts:['Proiectarea si executarea instalatiilor electrice de joasa tensiune','Doar panouri PV','Reteaua de gaz','Apa potabila'], correct:0,
    explain:'I7 este normativul pentru instalatii electrice de joasa tensiune.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Protectia la supracurent acopera:',
    opts:['Doar fuga la pamant','Suprasarcina si scurtcircuit','Doar supratensiunea','Doar caderea de tensiune'], correct:1,
    explain:'Supracurentul include atat suprasarcina cat si scurtcircuitul.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Un descarcator (SPD) Tip 1 se monteaza in principal pentru:',
    opts:['Curenti de fuga','Trasnet direct (cladiri cu paratrasnet)','Suprasarcina','Cadere de tensiune'], correct:1,
    explain:'SPD Tip 1 face fata curentilor de trasnet direct (forma 10/350).' },
  { level:'expert', cat:'Electrica', type:'single', q:'Un descarcator (SPD) Tip 2 protejeaza in principal la:',
    opts:['Trasnet direct','Supratensiuni de comutatie si trasnet indirect','Scurtcircuit','Subtensiune'], correct:1,
    explain:'SPD Tip 2 limiteaza supratensiunile induse si de comutatie.' },
  { level:'expert', cat:'Electrica', type:'single', q:'De ce timpul de declansare la atingere indirecta trebuie sa fie scurt?',
    opts:['Ca tensiunea de atingere periculoasa sa nu persiste pe corp','Ca sa creasca productia','Ca sa scada factura','Fara motiv'], correct:0,
    explain:'Declansarea rapida limiteaza durata expunerii la tensiunea de atingere.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Intr-o schema cu pornire directa, releul termic se regleaza la:',
    opts:['De 10 ori curentul nominal','Aproximativ curentul nominal al motorului','La tensiunea retelei','La zero'], correct:1,
    explain:'Releul termic se regleaza in jurul curentului nominal al motorului.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Caderea de tensiune pe un cablu monofazat se calculeaza tinand cont de:',
    opts:['Traseul dus-intors (de doua ori lungimea)','Doar dus','Doar culoare','Frecventa'], correct:0,
    explain:'La monofazat se considera lungimea dus-intors a conductorului.' },

  // ====================== EXPERT - FOTOVOLTAICE ======================
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Cum se modifica tensiunea de mers in gol (Voc) a panourilor cand temperatura scade?',
    opts:['Voc creste la temperaturi joase','Voc scade la frig','Ramane constanta','Devine zero'], correct:0,
    explain:'Coeficientul de temperatura e negativ: la frig Voc creste.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'De ce se dimensioneaza numarul de panouri pe string la temperatura MINIMA?',
    opts:['Pentru ca atunci Voc e maxima si nu trebuie depasita tensiunea invertorului','Ca sa fie mai ieftin','Pentru estetica','Fara motiv tehnic'], correct:0,
    explain:'La frig Voc creste; stringul nu trebuie sa depaseasca tensiunea maxima DC a invertorului.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Pentru numarul minim de panouri pe string, se verifica la temperatura:',
    opts:['Minima','Maxima de functionare (cand Vmpp scade)','Camerei','Nu se verifica'], correct:1,
    explain:'La cald Vmpp scade; stringul trebuie sa ramana peste tensiunea de pornire MPPT.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Curentul de scurtcircuit al unui panou (Isc) este:',
    opts:['Curentul la borne legate scurt, putin peste Impp','Zero','Egal cu tensiunea','Curentul din baterie'], correct:0,
    explain:'Isc este curentul la scurtcircuit, putin mai mare decat Impp.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Curentul nominal al sigurantei fuzibile de string se alege:',
    opts:['Mult sub Isc','Intre Isc si curentul maxim admis de cablu, conform fisei panoului','Egal cu tensiunea','La intamplare'], correct:1,
    explain:'Siguranta string se alege peste Isc dar sub limita cablului/panoului.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Sigurante de string DC devin necesare in special cand sunt:',
    opts:['Un singur string','Doua sau mai multe stringuri in paralel','Doar un panou','Doar baterie'], correct:1,
    explain:'La mai multe stringuri in paralel apare curent de retur ce trebuie protejat.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Dimensionarea bateriei de stocare se face in principal dupa:',
    opts:['Greutatea panourilor','Consumul de acoperit si autonomia dorita (kWh)','Culoarea invertorului','Numarul de prize'], correct:1,
    explain:'Bateria se dimensioneaza dupa energia de consum si autonomia ceruta.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'La o baterie litiu, adancimea de descarcare (DoD) utila este uzual:',
    opts:['Sub 10%','Aproximativ 80-95%','Exact 50% fix','Peste 100%'], correct:1,
    explain:'Bateriile litiu permit DoD ridicat, uzual 80-95%.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Eficienta unui invertor fotovoltaic modern este tipic:',
    opts:['Sub 50%','Aproximativ 95-98%','Exact 100%','In jur de 70%'], correct:1,
    explain:'Invertoarele moderne au randament tipic 95-98%.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Pierderile pe cablul DC cresc atunci cand:',
    opts:['Sectiunea e mare','Curentul si lungimea cresc, sectiunea e mica','Tensiunea e mare','Soarele e slab'], correct:1,
    explain:'Pierderile P=I^2*R cresc cu curentul, lungimea si rezistenta cablului.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'De ce stringurile lungi (multe panouri in serie) au pierderi DC relativ mici?',
    opts:['Tensiunea mai mare inseamna curent mai mic pentru aceeasi putere','Au mai mult cupru','Nu produc caldura','Curentul creste'], correct:0,
    explain:'La putere data, tensiune mai mare inseamna curent mai mic, deci pierderi I^2*R mai mici.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Coeficientul de temperatura al puterii (Pmax) unui panou siliciu este:',
    opts:['Pozitiv (creste cu caldura)','Negativ (puterea scade cu cresterea temperaturii)','Zero','Variabil cu culoarea'], correct:1,
    explain:'Puterea panoului scade cand temperatura celulei creste (coeficient negativ).' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Ce reprezinta PR (Performance Ratio) al unei centrale fotovoltaice?',
    opts:['Pretul panoului','Raportul intre energia reala produsa si cea teoretica','Numarul de panouri','Tensiunea stringului'], correct:1,
    explain:'PR compara productia reala cu cea teoretica ideala, indicand calitatea sistemului.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'In regim de prosumator, energia injectata in retea este:',
    opts:['Pierduta','Compensata/decontata cu furnizorul conform reglementarii','Stocata in panou','Transformata in caldura'], correct:1,
    explain:'Energia injectata se deconteaza cu furnizorul conform schemei prosumatorului.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'De ce se prefera autoconsumul fata de injectia in retea, economic?',
    opts:['Pretul energiei consumate evitate e de obicei mai mare ca cel al injectiei','Injectia e gratuita','Nu exista diferenta','Autoconsumul e interzis'], correct:0,
    explain:'Evitarea cumpararii (autoconsum) valoreaza uzual mai mult decat pretul injectiei.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Un descarcator (SPD) pe partea DC trebuie sa fie de tip:',
    opts:['Dedicat fotovoltaic, pentru tensiune DC','Orice SPD de AC','Fara importanta','De telefonie'], correct:0,
    explain:'SPD-ul DC fotovoltaic e proiectat pentru tensiunile DC si stingerea arcului DC.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Ce este efectul PID (Potential Induced Degradation) la panouri?',
    opts:['Crestere de productie','Degradare cauzata de tensiuni mari fata de pamant','Racire a panoului','Curatare automata'], correct:1,
    explain:'PID este degradarea cauzata de potentiale mari fata de pamant, scazand productia.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Verificarea polaritatii inainte de a conecta stringul la invertor este importanta pentru ca:',
    opts:['Polaritatea inversata poate deteriora invertorul sau impiedica functionarea','Schimba culoarea cablului','Mareste tensiunea retelei','Nu conteaza'], correct:0,
    explain:'Polaritatea inversa pe DC poate defecta invertorul si trebuie verificata.' },

  // ====================== PRO - ELECTRICA (extra) ======================
  { level:'pro', cat:'Electrica', type:'single', q:'Ce sectiune de cablu se recomanda uzual pentru un circuit de prize protejat la 20 A?',
    opts:['0,75 mmp','1,5 mmp','1 mmp','2,5 mmp'], correct:3,
    explain:'2,5 mmp suporta uzual 20 A in conditii normale de pozare.' },
  { level:'pro', cat:'Electrica', type:'single', q:'La un cablu de 6 mmp, ce siguranta automata se foloseste uzual?',
    opts:['10 A','16 A','20 A','32 A'], correct:3,
    explain:'6 mmp suporta uzual pana la 32-40 A; tipic 32 A.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Ce semnaleaza un releu termic care a declansat la un motor?',
    opts:['Tensiune prea mica','O suprasarcina prelungita pe motor','Lipsa nulului','Frecventa gresita'], correct:1,
    explain:'Declansarea termica indica un curent prea mare timp indelungat pe motor.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Bobina de comanda a unui contactor de 230 V se alimenteaza intre:',
    opts:['Doua faze de 400 V','Faza si nul (230 V)','Doua PE-uri','Faza si PE'], correct:1,
    explain:'O bobina de 230 V se alimenteaza intre faza si nul.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Cablul CYY se foloseste uzual pentru:',
    opts:['Antene TV','Pozare in interior, in tub sau aparent, fara armatura','Pozare directa in pamant fara protectie','Linii aeriene de inalta tensiune'], correct:1,
    explain:'CYY este cablu de energie nearmat pentru interior/aparent sau in tub.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Intr-o schema cu auto-mentinere, daca se intrerupe alimentarea si revine, motorul:',
    opts:['Porneste singur automat','Ramane oprit pana la o noua apasare pe START','Isi schimba sensul','Se arde'], correct:1,
    explain:'Auto-mentinerea cade la disparitia tensiunii, deci e nevoie de o noua comanda START.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Pentru un boiler electric de 2 kW pe 230 V, ce siguranta este potrivita?',
    opts:['6 A','10 A','16 A','40 A'], correct:2,
    explain:'2000/230 = aprox 9 A; se foloseste uzual 16 A pe 2,5 mmp.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Cum se conecteaza becul fata de intrerupator si priza?',
    opts:['Becul in serie cu priza','Faza prin intrerupator la bec, nul direct la bec','Nulul prin intrerupator','PE prin intrerupator'], correct:1,
    explain:'Faza trece prin intrerupator spre bec, nulul merge direct la bec.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Ce este o schema desfasurata (de comanda) fata de cea monofilara?',
    opts:['Aceeasi schema','Arata detaliat circuitul de comanda, contact cu contact','Arata doar bateria','Doar lista de materiale'], correct:1,
    explain:'Schema desfasurata detaliaza logica de comanda, contact cu contact.' },
  { level:'pro', cat:'Electrica', type:'single', q:'Un RCD declanseaza des, fara defect aparent. O cauza frecventa este:',
    opts:['Sectiune prea mare','Curenti de fuga cumulati de la mai multi consumatori','Siguranta prea mica','Lipsa fazei'], correct:1,
    explain:'Fugile mici cumulate de la mai multi consumatori pot depasi pragul RCD.' },
  { level:'pro', cat:'Electrica', type:'single', q:'La un tablou trifazat se urmareste echilibrarea fazelor pentru a:',
    opts:['Creste tensiunea','Distribui uniform consumul pe L1, L2, L3','Elimina nulul','Mari frecventa'], correct:1,
    explain:'Echilibrarea distribuie sarcina uniform si reduce curentul pe nul.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Daca pui prea putine panouri pe un string, riscul este:',
    opts:['Tensiunea sub pragul de pornire MPPT al invertorului','Distrugerea panourilor','Cresterea curentului periculos','Nimic'], correct:0,
    explain:'Tensiunea prea mica a stringului poate fi sub fereastra MPPT, deci invertorul nu porneste optim.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Raportul DC/AC supraunitar (oversizing) al panourilor fata de invertor:',
    opts:['Este intotdeauna gresit','Poate creste productia in orele slabe, cu un mic clipping la varf','Distruge invertorul mereu','Scade tensiunea'], correct:1,
    explain:'Un oversizing moderat valorifica mai bine invertorul, cu un clipping limitat la varf.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Ce verifici inainte de a paraleliza doua stringuri pe acelasi MPPT?',
    opts:['Culoarea panourilor','Sa aiba aproximativ aceeasi tensiune (acelasi numar de panouri)','Sa fie de la furnizori diferiti','Greutatea'], correct:1,
    explain:'Stringurile in paralel trebuie sa aiba tensiuni apropiate, deci acelasi numar de panouri.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'La un invertor cu doua MPPT-uri, doua versante de acoperis diferite se leaga:',
    opts:['Toate pe un singur MPPT','Cate un versant pe fiecare MPPT','In serie obligatoriu','Direct la baterie'], correct:1,
    explain:'Fiecare versant pe MPPT propriu, ca sa fie optimizat separat.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Sectiunea cablului solar DC se alege pentru a limita:',
    opts:['Greutatea','Caderea de tensiune si pierderile pe traseu','Culoarea','Numarul de conectori'], correct:1,
    explain:'O sectiune corecta tine caderea de tensiune si pierderile DC in limite acceptabile.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Intr-un sistem hibrid, prioritatea uzuala de folosire a energiei este:',
    opts:['Retea, apoi baterie, apoi consum','Autoconsum, apoi incarcare baterie, apoi injectie in retea','Doar injectie','Doar baterie'], correct:1,
    explain:'Tipic: intai consumul casei, apoi incarcarea bateriei, apoi surplusul in retea.' },
  { level:'pro', cat:'Fotovoltaice', type:'single', q:'Ce protectie AC se monteaza la iesirea invertorului on-grid?',
    opts:['Doar un intrerupator de lumina','Siguranta automata si, dupa caz, diferential','Niciuna','Un contor de apa'], correct:1,
    explain:'Iesirea AC a invertorului se protejeaza cu siguranta automata si diferential dupa caz.' },

  // ====================== EXPERT - ELECTRICA (extra) ======================
  { level:'expert', cat:'Electrica', type:'single', q:'In sistemul TN, protectia la atingere indirecta se bazeaza in principal pe:',
    opts:['Curentul mare de defect ce face protectia la supracurent sa declanseze rapid','Lipsa prizei de pamant','Doar RCD obligatoriu','Tensiune crescuta'], correct:0,
    explain:'In TN, bucla de defect are impedanta mica, deci protectia la supracurent declanseaza rapid.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Pentru selectivitate totala intre doua RCD-uri pe verticala, cel din amonte trebuie sa fie:',
    opts:['De acelasi tip si prag','Cu prag mai mare si temporizat (tip S, selectiv)','Mai sensibil','Fara importanta'], correct:1,
    explain:'RCD-ul din amonte trebuie sa fie de tip selectiv (S), temporizat si cu prag mai mare.' },
  { level:'expert', cat:'Electrica', type:'single', q:'O cadere de tensiune de 8% pe un circuit de forta lung indica:',
    opts:['Situatie normala','Subdimensionarea sectiunii; trebuie marita','Tensiune prea mare','Lipsa PE'], correct:1,
    explain:'8% depaseste limita de 5%; sectiunea trebuie marita pentru a reduce caderea.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Compensarea capacitiva excesiva (supracompensare) duce la:',
    opts:['cos fi unitar perfect','Factor de putere capacitiv si posibile supratensiuni','Lipsa de curent','Frecventa zero'], correct:1,
    explain:'Supracompensarea face instalatia capacitiva si poate produce supratensiuni.' },
  { level:'expert', cat:'Electrica', type:'single', q:'La pornirea directa, curentul de pornire al unui motor asincron este tipic:',
    opts:['Egal cu cel nominal','De 5-8 ori curentul nominal','Sub nominal','Zero'], correct:1,
    explain:'Pornirea directa da un curent de 5-8 ori In, de unde nevoia metodelor de pornire lina.' },
  { level:'expert', cat:'Electrica', type:'single', q:'In conexiunea stea, tensiunea pe infasurarea motorului fata de conexiunea triunghi este:',
    opts:['Mai mare','Mai mica (de radical 3 ori), deci curent de pornire redus','Egala','Zero'], correct:1,
    explain:'In stea, infasurarea primeste tensiune mai mica, reducand curentul de pornire.' },
  { level:'expert', cat:'Electrica', type:'single', q:'Verificarea continuitatii conductorului PE este importanta pentru ca:',
    opts:['Asigura calea de defect spre protectie la atingere indirecta','Mareste productia','Schimba culoarea','Reduce tensiunea de alimentare'], correct:0,
    explain:'Un PE intrerupt nu permite declansarea protectiei la un defect de izolatie.' },
  { level:'expert', cat:'Electrica', type:'single', q:'SPD-ul de tip combinat 1+2 se foloseste cand:',
    opts:['Nu exista risc de trasnet','Se doreste protectie la trasnet direct si la supratensiuni induse intr-un singur aparat','Doar pentru DC','Doar pentru iluminat'], correct:1,
    explain:'SPD 1+2 acopera atat curentii de trasnet direct cat si supratensiunile induse.' },

  // ====================== EXPERT - FOTOVOLTAICE (extra) ======================
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'La calculul numarului maxim de panouri in serie se foloseste Voc corectat la temperatura minima a sitului, pentru a:',
    opts:['Mari productia','Nu depasi tensiunea maxima DC a invertorului in cea mai rece zi','Reduce numarul de panouri inutil','Schimba polaritatea'], correct:1,
    explain:'In ziua cea mai rece Voc e maxima; stringul nu trebuie sa depaseasca limita invertorului.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Pierderile pe cablul DC se reduc cel mai eficient prin:',
    opts:['Cresterea curentului','Marirea sectiunii si scurtarea traseului','Reducerea tensiunii stringului','Mai multi conectori'], correct:1,
    explain:'Sectiune mai mare si traseu scurt reduc rezistenta si pierderile I^2*R.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Eficienta europeana (Euro eta) a unui invertor descrie:',
    opts:['Doar randamentul la putere maxima','Randamentul ponderat pe diferite niveluri de incarcare','Pretul','Tensiunea de iesire'], correct:1,
    explain:'Euro eta pondereaza randamentul pe regimuri partiale, reflectand functionarea reala.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Dimensionarea bateriei pentru autonomie de o seara se face calculand:',
    opts:['Numarul de panouri','Energia consumata in acel interval, plus rezerva si DoD util','Tensiunea retelei','Curentul de scurtcircuit'], correct:1,
    explain:'Se pleaca de la energia de consum din interval, ajustata cu DoD util si pierderi.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'Curentul invers admis de un panou (reverse current) limiteaza:',
    opts:['Tensiunea de iesire','Numarul de stringuri ce pot fi paralelizate fara sigurante','Greutatea','Culoarea celulei'], correct:1,
    explain:'Curentul invers admis dicteaza cate stringuri se pot paraleliza inainte de a fi nevoie de sigurante.' },
  { level:'expert', cat:'Fotovoltaice', type:'single', q:'La temperaturi ridicate ale celulei, randamentul real al panoului:',
    opts:['Creste','Scade fata de conditiile standard (STC)','Ramane neschimbat','Devine negativ'], correct:1,
    explain:'Caldura excesiva reduce tensiunea si puterea, deci randamentul scade fata de STC.' },

  // ====================== DRAG & DROP ======================
  { level:'beginner', cat:'Electrica', type:'drag', q:'Trage fiecare culoare pe conductorul corect:',
    tokens:[{id:'rosu',label:'Maro (faza)'},{id:'albastru',label:'Albastru'},{id:'gv',label:'Galben-verde'}],
    slots:[{id:'faza',label:'Faza (L)',accept:'rosu'},{id:'nul',label:'Nul (N)',accept:'albastru'},{id:'pe',label:'Impamantare (PE)',accept:'gv'}],
    explain:'Faza = maro/negru, nul = albastru, PE = galben-verde.' },
  { level:'beginner', cat:'Electrica', type:'drag', q:'Potriveste siguranta corecta pentru fiecare circuit:',
    tokens:[{id:'a10',label:'10 A'},{id:'a16',label:'16 A'},{id:'a25',label:'25 A'}],
    slots:[{id:'ilum',label:'Iluminat (1,5 mmp)',accept:'a10'},{id:'prize',label:'Prize (2,5 mmp)',accept:'a16'},{id:'cuptor',label:'Cuptor (4 mmp)',accept:'a25'}],
    explain:'1,5 mmp -> 10 A, 2,5 mmp -> 16 A, 4 mmp -> 25 A.' },
  { level:'beginner', cat:'Fotovoltaice', type:'drag', q:'Trage fiecare componenta la rolul ei in sistemul fotovoltaic:',
    tokens:[{id:'panou',label:'Panou PV'},{id:'invertor',label:'Invertor'},{id:'baterie',label:'Baterie'}],
    slots:[{id:'dc',label:'Produce curent continuu (DC)',accept:'panou'},{id:'conv',label:'Transforma DC in AC',accept:'invertor'},{id:'stoc',label:'Stocheaza energie (kWh)',accept:'baterie'}],
    explain:'Panoul produce DC, invertorul il transforma in AC, bateria stocheaza energia.' },
  { level:'pro', cat:'Electrica', type:'drag', img:SVG_MOTOR, q:'Leaga fazele la motor ca sa se invarta spre DREAPTA (U=L1, V=L2, W=L3):',
    tokens:[{id:'l1',label:'L1'},{id:'l2',label:'L2'},{id:'l3',label:'L3'}],
    slots:[{id:'U',label:'Borna U',accept:'l1'},{id:'V',label:'Borna V',accept:'l2'},{id:'W',label:'Borna W',accept:'l3'}],
    explain:'Ordinea L1-L2-L3 pe U-V-W da rotatie spre dreapta. Inversezi doua faze pentru sensul invers.' },
  { level:'pro', cat:'Electrica', type:'drag', q:'Aseaza aparatele in ordinea corecta in tablou, de la retea spre circuite:',
    tokens:[{id:'gen',label:'Siguranta generala'},{id:'rcd',label:'Diferential (RCD)'},{id:'circ',label:'Siguranta de circuit'}],
    slots:[{id:'s1',label:'1. Primul de la retea',accept:'gen'},{id:'s2',label:'2. Al doilea',accept:'rcd'},{id:'s3',label:'3. Spre consumator',accept:'circ'}],
    explain:'Ordinea corecta: general -> diferential -> sigurante pe circuite.' },
  { level:'expert', cat:'Electrica', type:'drag', q:'Asociaza fiecare sistem de legare la pamant cu descrierea corecta:',
    tokens:[{id:'tns',label:'TN-S'},{id:'tncs',label:'TN-C-S'},{id:'tt',label:'TT'}],
    slots:[{id:'d1',label:'N si PE separate pe tot traseul',accept:'tns'},{id:'d2',label:'PEN combinat, apoi separat in N si PE',accept:'tncs'},{id:'d3',label:'Priza de pamant locala proprie',accept:'tt'}],
    explain:'TN-S: N si PE separate; TN-C-S: PEN apoi separat; TT: priza de pamant proprie.' },
  { level:'expert', cat:'Fotovoltaice', type:'drag', q:'Asociaza fiecare protectie DC cu rolul ei:',
    tokens:[{id:'fuz',label:'Siguranta fuzibila DC'},{id:'sect',label:'Sectionator DC'},{id:'spd',label:'Descarcator SPD'}],
    slots:[{id:'r1',label:'Protejeaza stringul la supracurent',accept:'fuz'},{id:'r2',label:'Separa panourile de invertor',accept:'sect'},{id:'r3',label:'Protejeaza la supratensiuni',accept:'spd'}],
    explain:'Fuzibil = supracurent, sectionator = separare, SPD = supratensiuni.' }
];
